### ISSUE TITLE
2015-12-15開催の「OSS Gateを立ち上げよう」のログをpushする

### ISSUE THREAD

**Issue by kou** [oss-gate/meetup#1]
@sezemiadmin 昨日とってもらっていたログを https://github.com/oss-gate/meetup/tree/master/2015-12-15/ の下にpushしてもらえますか！？「New file」というボタンを使えばWebブラウザー上からできるんじゃないかと思います！わからなかったら聞いてください。だれか教えてくれるはずです！

**Comment by sezemiadmin** [comment]
@kou 書いてみました! https://github.com/oss-gate/meetup/blob/master/2015-12-15/log

**Comment by sezemiadmin** [comment]
@satoryu markdown形式への変更ありがとうございます!(知らなかったです

**Comment by kou** [comment]
ありがとうございます！
